### ISSUE TITLE
Adding another portfolio

### ISSUE THREAD

**Issue by srigurubyo** [kishaningithub/hugo-creative-portfolio-theme#43]
Hi, thanks for this wonderful and yet simple theme!

I just want to know is there a way to add another portfolio (eg: stocks and bonds) to the theme?  Each portfolio will have different set of cards of course.

Thanks in advance for your help here!

**Comment by kishaningithub** [comment]
@srigurubyo Thanks!

To answer your question - nope.

**Comment by clukeh** [comment]
Is this what you are after?

https://algo.ulb.be/

This site has three portfolios, each one running from a link on the left.

Regards

**Comment by srigurubyo** [comment]
Yes

**Comment by kishaningithub** [comment]
@clukeh Nice one! @srigurubyo

**Comment by srigurubyo** [comment]
Is that on GitHub?

**Comment by clukeh** [comment]
Hi Kishan,

Adding that feature will be fantastic....looking forward to it.

I should add that the Belgian site is not mine - it's one I spotted and liked their enhancement.

Kind regards :-)

**Comment by kishaningithub** [comment]
@srigurubyo @clukeh 

#### config.toml

```toml
  # Nav links in the side bar
  [[params.navlinks]]
  name = "Portfolio 1"
  url = "portfolio/"
  home = true

  [[params.navlinks]]
  name = "Portfolio 2"
  url = "another-portfolio/"

```

Note the new `home=true` flag. This flag indicates which among your portfolios is your root URL

#### End result 

![screen shot 2018-05-06 at 1 58 38 pm](https://user-images.githubusercontent.com/763760/39671555-230447e6-5138-11e8-9c79-2a96bea005b0.png)
